### ISSUE TITLE
Use a fixed name for the application in the container

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus-images#11]
Currently the S2I image the native output `*-runner` to a directory making the final native application name depending on the maven output. This makes it harder to create for example a chained build since input from a chained build cannot contain wildcards. I suggest changing the name of the application to `/home/quarkus/application`

**Comment by vorburger** [comment]
This makes sense to me.

**Comment by vorburger** [comment]
@tqvarnst can you close this issue - with the merge of #12 this is effectively done (in the `graalvm-1.0.0-rc15` branch) - agreed?

**Comment by tqvarnst** [comment]
Fixed in branch 1.0.0-rc15
