### ISSUE TITLE
Mandrel 20.3.0.0.Beta1-java11: Could not find agent library native-image-diagnostics-agent

### ISSUE THREAD

**Issue by sherl0cks** [quarkusio/quarkus-images#114]
Building a native image results in:
```
Error occurred during initialization of VM
Could not find agent library native-image-diagnostics-agent on the library path, with error: libnative-image-diagnostics-agent.so: cannot open shared object file: No such file or directory
Error: Image build request failed with exit status 1
```

Issue is not present on mandrel 20.2-java11.

**Comment by zakkak** [comment]
Hi @sherl0cks,
Did you use any special flags like `-Dquarkus.native.additional-build-args='--trace-object-instantiation=...'`?

**Comment by sherl0cks** [comment]
@zakkak I did have that one but it broke for a different reason. When removed, I got this error. Here is my current setting:
`quarkus.native.additional-build-args=--initialize-at-run-time=java.awt.image.AreaAveragingScaleFilter,-H:DynamicProxyConfigurationFiles=dynamic-proxy.json,-H:ResourceConfigurationFiles=resources-config.json,-H:ReflectionConfigurationFiles=reflection-config.json,--report-unsupported-elements-at-runtime`

**Comment by zakkak** [comment]
Oh, then it's probably `--report-unsupported-elements-at-runtime` that
needs the agent.

**Comment by sherl0cks** [comment]
K will try without it and report back. Thanks for the quick replies @zakkak

**Comment by sherl0cks** [comment]
OK so removing `--report-unsupported-elements-at-runtime` gets the image to build, but I still have AWT issues as described in https://github.com/graalvm/mandrel/issues/180. For now, leaving this issue open because it does seem to be a regression from 20.2 where `--report-unsupported-elements-at-runtime` works fine.
