### ISSUE TITLE
CI with integration tests of (all, "supported") Quarkus Docker images

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus-images#14]
#13 made me think that, in an ideal world, we should have CI with integration tests of (all, "supported") Quarkus Docker images ... so that should, ultimately, include the:

1. Native S2I (whose sources are here in this repo)
2. Java S2I (based on `registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift`)
3. Q: any non-S2I support Docker base images we produce here?

@cescoffier @tqvarnst

**Comment by cescoffier** [comment]
CI has been implemented
