### ISSUE TITLE
s2i native MVN_ADDITIONAL_ARGS

### ISSUE THREAD

**Issue by alegug** [quarkusio/quarkus-images#158]
Trying to build a native image usinng s2i but can't set my own settings.xml for authenticate my own repository. I saw this variable MVN_ADDITIONAL_ARGS in the mvn package assembly script but it does not the setting value. What I can see is that its not defined in the module.yml.
Could it be added?

**Comment by cescoffier** [comment]
Adding it to the `module.yml` won't help. What are you trying to do? You can pass `MVN_ADDITIONAL_ARGS` as environment variables.

**Comment by alegug** [comment]
Hi, Thanks for the fast response. What i am trying to do is compile and connect to a private package registry using s2i native image. I am trying to use my own settings.xml with my access token configuration. You are correct,  MVN_ADDITIONAL_ARGS work well, I made a typo and write MVN_ADDITIONAL_ARG without the las S. Thanks and sorry.
