### ISSUE TITLE
multi-arch images missing manifest list?

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-images#199]
I see on https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags (as well as some of the other images on quay.io/quarkus) there are multi-arch images, but I don't see a manifest list that combines the images.

As it is now I have to specify a specific image tag for amd64 vs arm64 instead of just saying `quay.io/quarkus/ubi-quarkus-mandrel:22.0-java17` and let it figure out which platform to build.

For example, from https://quay.io/repository/quarkus-super-heroes/rest-villains?tab=tags

![image](https://user-images.githubusercontent.com/363447/176962722-66dd6125-8f02-47c2-9ac2-1b7f3adf0854.png)

**Comment by cescoffier** [comment]
@edeandrea we are working on a new approach to produce multi-arch images. The current approach is not convenient (and upx does not have the right arch)

**Comment by cescoffier** [comment]
Fixed.
