### ISSUE TITLE
Support for java8 based images

### ISSUE THREAD

**Issue by tasadurian** [quarkusio/quarkus-images#211]
Is there a plan to support `java8` in the new images? We have been using `centos-quarkus-maven:*-java8` as a base for some applications and would like to upgrade for multi-arch support. I don't see any images tagged with `java8` at this time.

**Comment by cescoffier** [comment]
No, this image is not maintained anymore:

- Quarkus does not support java 8 since several versions 
- this image was always outdated as it included many tools
- doing a multi-archs variants would be pretty hard as some of the included tools are not easy to run on multi-archs (native dependencies)
