### ISSUE TITLE
Increase in quarkus mandrel images - version 21.2.x

### ISSUE THREAD

**Issue by gansheer** [quarkusio/quarkus-images#220]
The apache/camel-k project using the quarkus mandrel `quarkus/ubi-quarkus-mandrel` java 11 image as parent image [its own](https://github.com/apache/camel-k/blob/main/build/Dockerfile). We observed an increase in the size of this image on the `21.2.x` version from ~320MB to ~560MB coupled with changes in the layers (june 2022) :

* 21.2.0.1-Final-java11 : 322.7 MB / https://quay.io/repository/quarkus/ubi-quarkus-mandrel/manifest/sha256:aa9b3d4e0ebf86da388c7ba4f98700324a17f351f02e571065e823b261a861cd
* 21.2.0.2-Final-java11 : 323.7 MB / https://quay.io/repository/quarkus/ubi-quarkus-mandrel/manifest/sha256:d8e1f69c9311533b722a4d9f64bf795a8690cffa2eb118190b9fbcde913cf956 (there are some COPY ... /tmp in the new layers)

Could you please provide some inputs on the reason for this increase in size and the change in layers ?

_The camel-k project issue : [apache/camel-k/issues/3925](https://github.com/apache/camel-k/issues/3925)_

**Comment by cescoffier** [comment]
I've checked the latest image and the content of /tmp is 176Kb, so that's not explaining the size difference. 

What's important to notice is the size of the mandrel directory (/opt/mandrel): 437Mb.

**Comment by cescoffier** [comment]
The jump in size happened between 22.0 and 22.1. With 22.1, we started handling ARM images and we had to stop (for some other technical reason) so squash the layers. This is the reason for the size difference.

Note that not squashing only increases the download times when the image is not present. Subsequent updates will rely on the cached layers.

**Comment by gansheer** [comment]
Thank you for your answer.
