### ISSUE TITLE
Delete generic tags from the old ubi-quarkus-mandrel to prevent confusion

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus-images#223]
Hello,

## Problem

It has caught my eye recently that various automation scripts of mine were erroneously pulling [ubi-quarkus-mandrel](https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags) instead of [ubi-quarkus-mandrel-builder-image](https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags), effectively testing obsolete images. I fixed it for me, although I can imagine there are numerous people out there who just won't notice. See:

```
$ docker run quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 --version 
native-image 22.3.1.0-Final Mandrel Distribution (Java Version 17.0.6+10)

$ docker run quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17 --version
native-image 22.3.0.1-Final Mandrel Distribution (Java Version 17.0.5+8)

$ docker run quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17 --version
native-image 21.3.3.0-Final Mandrel Distribution (Java Version 17.0.4+8)

$ docker run quay.io/quarkus/ubi-quarkus-mandrel-builder-image:21.3-java17 --version
native-image 21.3.5.1-Final Mandrel Distribution (Java Version 17.0.6+10)
```
...all work just fine, although users are getting obsolete images from `ubi-quarkus-mandrel`.

## Possible solutions

I wonder whether to disable the old [ubi-quarkus-mandrel](https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags) registry altogether or perhaps at least to delete these tags from `ubi-quarkus-mandrel`: 22.3-java17, 21.3-java17 and 21.3-java11.

WDYT?

**Comment by jerboaa** [comment]
Up to date images are only available via repository `quay.io/quarkus/ubi-quarkus-mandrel-builder-image` and it would be best to only have generic (moving tags) from the repo which actually contains up-to-date images. +1.

**Comment by cescoffier** [comment]
As the image update was done in September, I agree. Let's remove these floating tags. 

I just did it for the old graalvm CE and mandrel build images.

**Comment by jerboaa** [comment]
> I just did it for the old graalvm CE and mandrel build images.

Thanks. The 21.3 images are still pull-able via the generic tags?

```
$ podman pull quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17...
Getting image source signatures
Copying blob 7bde46c9d502 done  
Copying blob 2e0041d47725 done  
Copying blob c7ffde22fa6c done  
Copying blob 008dba906bf6 skipped: already exists  
Copying blob 5f9bab1b9845 done  
Copying blob d5d2e87c6892 skipped: already exists  
Copying blob b4a9a20e16de done  
Copying blob 050bc59b2eed done  
Copying blob 7a44d33baf2d done  
Copying blob 1a1f3fafa39c done  
Copying blob 42daaf843bfc done  
Copying blob ae719cb60142 done  
Copying blob f0c0f94e8cba done  
Copying blob d53de92a0e4c done  
Copying blob 5aea73b94398 done  
Copying blob 6f1fcba8c62b done  
Copying blob 6457c6fcaad8 done  
Copying blob 51d688024ea1 done  
Copying blob b01c90f0831c done  
Copying config 97e61c41b7 done  
Writing manifest to image destination
Storing signatures
97e61c41b7bb1998e13a9b61f74da7074970dc79f5a3ab9088bbd761b4860f06
$ podman run --rm -ti quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17 --version
native-image 21.3.3.0-Final Mandrel Distribution (Java Version 17.0.4+8)
$ $ podman pull quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11...
Getting image source signatures
Copying blob 7bde46c9d502 skipped: already exists  
Copying blob 5f9bab1b9845 skipped: already exists  
Copying blob c7ffde22fa6c skipped: already exists  
Copying blob b4a9a20e16de skipped: already exists  
Copying blob 7a44d33baf2d skipped: already exists  
Copying blob 008dba906bf6 skipped: already exists  
Copying blob 2e0041d47725 skipped: already exists  
Copying blob 050bc59b2eed skipped: already exists  
Copying blob 1a1f3fafa39c skipped: already exists  
Copying blob ae719cb60142 skipped: already exists  
Copying blob 42daaf843bfc skipped: already exists  
Copying blob 047a9cba122d done  
Copying blob 954e5140fe7f done  
Copying blob a7f841c5d23e done  
Copying blob 9bf75fb6185a done  
Copying blob 600fe3135a3f done  
Copying blob d5d2e87c6892 skipped: already exists  
Copying blob e3770fd88680 done  
Copying blob ab9d7db14f5c done  
Copying config b233b61a62 done  
Writing manifest to image destination
Storing signatures
b233b61a624d808c169ad2781c701279ac860eaab73c30d95b3cc8791e3b6ad0
$ podman run --rm -ti quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11 --version
native-image 21.3.3.0-Final Mandrel Distribution (Java Version 11.0.16+8)
```

Both are outdated :-(

**Comment by cescoffier** [comment]
I just delete 22.3.

**Comment by jerboaa** [comment]
> I just delete 22.3.

Could you please delete floating tags for 21.3 too? Those are builds with 2 security fixes behind and users shouldn't use them, but migrate to `quay.io/quarkus/ubi-quarkus-mandrel-builder-image`. 21.3 images on the new location are up-to-date.

**Comment by zakkak** [comment]
Quarkus 2.13 [relies on 22.3-java17 tags of  `quay.io/quarkus/ubi-quarkus-mandrel`](
https://github.com/quarkusio/quarkus/blob/4196737b2d12f38f5a030722fd0c80b6d945db19/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L19-L20) so deleting these tags results in https://github.com/quarkusio/quarkus/issues/30738.

So we need to either update these images as well or update 2.13 to work with `quay.io/quarkus/ubi-quarkus-mandrel-builder-image`.

**Comment by jerboaa** [comment]
Interesting. So it seems not even the prime consumer of those images (quarkus) failed to make the switch? Sigh. +1 on moving to the correct (and maintained) new default: `quay.io/quarkus/ubi-quarkus-mandrel-builder-image`.
