### ISSUE TITLE
S2I Maven configure.sh not found

### ISSUE THREAD

**Issue by floriansiepe** [quarkusio/quarkus-images#224]
When trying to build a Quarkus 2.16 application with the `quay.io/quarkus/ubi-quarkus-graalvmce-s2i:22.3-java17` image inside an Openshift cluster it throws:
```
STEP 4/9: USER root
STEP 5/9: COPY upload/src /tmp/src
STEP 6/9: RUN chown -R 1001:0 /tmp/src
STEP 7/9: USER 1001
STEP 8/9: RUN /usr/libexec/s2i/assemble
+ CONFIGURE_SCRIPTS=(${APP_HOME}/.m2/configure-maven.sh)
+ source /home/quarkus/.m2/configure.sh
/usr/libexec/s2i/assemble: line 16: /home/quarkus/.m2/configure.sh: No such file or directory
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
```

Apparently it is referenced from [here](https://github.com/quarkusio/quarkus-images/blob/main/quarkus-native-s2i/src/main/resources/scripts/assemble).

However, in the latest [build logs](https://github.com/quarkusio/quarkus-images/actions/runs/4034256998/jobs/6935318655) I can spot a `configure-maven.sh` file being copied at some places. Is this just a typo in the `assemble` script?

**Comment by cescoffier** [comment]
Hum, these lines are really old leftovers. I've open a PR removing that.
