### ISSUE TITLE
republished Docker tags with image overwrites

### ISSUE THREAD

**Issue by dg-diconium** [quarkusio/quarkus-images#229]
We would really like to use the image quarkus-micro-image. But for this we need a fixed version to include it in our build pipelines and release processes. In our environment, concrete versions of transitive dependencies are tested and approved, so it is not acceptable to get a different delivery tomorrow than today.

Why are the published tags being overwritten? see https://quay.io/repository/quarkus/quarkus-micro-image?tab=history&tag=latest

Are there any concrete plans to switch to a normal release with version bumps as usual?

**Comment by dg-diconium** [comment]
Yes, using a tag would at least mitigate the issue, but then I would lose the convenience of an automatic update through Dependabot

What's wrong with using a latest tag and concrete versions? What do you have against it and why don't you use it as usual?

**Comment by cescoffier** [comment]
latest is the equivalent of snapshot. I build latest for development and local tests, but I cannot guarantee the stability. 

Also latest does not mean latest in term of version.

**Comment by cescoffier** [comment]
BTW, one issue with concrete version is that we will bump the version every week - which is ok when you have the tooling you need, but most of the time you will use a very outdated (potentially with lots of CVE) images.

**Comment by dg-diconium** [comment]
I can understand your argumentation, but it seems a bit out of touch with reality. 

Usually the image is used as a base image, which means that a project creates the container when the code base changes or a version of a dependency have to be updated. By replacing the tag, there is no way to find out that an update due to CVEs in the base image would be necessary or advisable. So the old containers continue to run until at some point a change to the sources makes a new build necessary.

I think for our case the image is not usable and I'll have to build an own one, based on ubi8-micro or ubi-minimal or direct on scratch, because we only build native.

One thing I would like to ask, Can you please describe the use of floating tags in Quarku's documentation? https://quarkus.io/guides/quarkus-runtime-base-image
This could be very helpful for others also facing this issue.

**Comment by cescoffier** [comment]
See https://github.com/quarkusio/quarkus-images/pull/233 and https://quay.io/repository/quarkus/quarkus-micro-image?tab=tags.

**Comment by cescoffier** [comment]
Can you confirm that would work for you?

**Comment by cescoffier** [comment]
@dg-diconium If I push another version today, would you be able to check?

**Comment by dg-diconium** [comment]
yes, I'll be

**Comment by cescoffier** [comment]
Done, you should see a 2.0-2023-04-26 version.

**Comment by dg-diconium** [comment]
Thanks a lot, works that way, see attached screenshot of the last auto merged build

<img width="846" alt="Screenshot 2023-04-26 at 18 51 46" src="https://user-images.githubusercontent.com/109366017/234661541-8ddbb528-bb10-4bdb-a79b-9afe79cd9fd9.png">

**Comment by cescoffier** [comment]
Awesome! I will merge the associated PR. 

Wondering if I should generalize that approach.

**Comment by zakkak** [comment]
> Wondering if I should generalize that approach.

+1

**Comment by cescoffier** [comment]
All done!
