### ISSUE TITLE
Using graalvm-ce tag jdk-17.0.7 cause issue at runtime

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus-images#241]
I am using the following image to build `quay.io/quarkus/ubi-quarkus-graalvmce-builder-image` in a multistage build that then is used with `quay.io/quarkus/quarkus-micro-image:2.0`

When using `quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.2-java17` and all the previous ones everything works, but when switching to `quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-17.0.7` I get the following.

```
# ktail
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option. 
```

**Comment by jerboaa** [comment]
Please try a build passing `-march=compatibility` to the native image build.

**Comment by manofthepeace** [comment]
> Please try a build passing -march=compatibility to the native image build.
That worked, thanks. I wonder if that should be a default in quarkus? or configurable separately.

**Comment by cescoffier** [comment]
@manofthepeace can you tell me where did you try to deploy? 
I've tested a few EC2 instance types, without any issues.

**Comment by manofthepeace** [comment]
The image was built using azure pipelines and was deployed in an private internal lab/k8s cluster we have. That lab have older blades / cpus and could be the issue. I will be on PTO next week but will see if I can try in azure, where we usually deploy and I can report back, but I think that might be a non issue there as well as you found in aws.
