### ISSUE TITLE
Is the "ubi-quarkus-graalvmce-s2i" image deprecated?

### ISSUE THREAD

**Issue by turbolocust** [quarkusio/quarkus-images#248]
The README says that only `centos-quarkus-maven` is discontinued. But when I go to [Quay](https://quay.io/repository/quarkus/ubi-quarkus-graalvmce-s2i?tab=info) it says:
> IMPORTANT: This image is deprecated and is plan for removal.

Is the `ubi-quarkus-graalvmce-s2i` image going to be discontinued?

**Comment by cescoffier** [comment]
Yes, this image is going to be removed in the future.
It embeds Maven and Gradle, which are hard to maintain (CVEs and so one) and are not very useful with maven and gradle wrappers. 

Also, the amount of memory required to build the application in native often exceeds the allowed limits.
