### ISSUE TITLE
quarkus / ubi-quarkus-graalvmce-s2i - Deprication Warning on quay.io

### ISSUE THREAD

**Issue by benoitschipper** [quarkusio/quarkus-images#250]
Hey all,

Just have a question. According to your documentation I did not see any mention of the future deprication of the "ubi-quarkus-graalvmce-s2i" image. However, when venturing to quay it states the following:

IMPORTANT: This image is deprecated and is plan for removal.
![image](https://github.com/quarkusio/quarkus-images/assets/77777295/3109179c-18a7-405d-969e-e8e78d1e139d)

Is this correct and if the image will eventually no longer be maintained, what are the timelines?

Thanks in advance :)

Benoit

**Comment by appiepollo14** [comment]
Very curious to know the answer as well!

**Comment by cescoffier** [comment]
While it's yet to be decided when this image is deprecated. 
Having to embed Maven and Gradle causes lots of issues and CVEs, and it is always out of date (and updates can break existing apps). 
In addition, this image generally requires some memory tuning to run in a cluster.

We will document the path forward, but, as explained in https://github.com/quarkusio/quarkus-images/issues/249, it's:

1. Build your executable and image
2. Push it to a repository
3. Adapt the descriptor to use this image

All three steps can be automated with Quarkus.

**Comment by benoitschipper** [comment]
Thanks @cescoffier ! Appreciate the feedback, I will take this back to the team and decide on how to proceed.
