### ISSUE TITLE
Configurable `workingDir` with s2i images

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus-images#26]
The current s2i assemble script does use `cd /tmp/src` as the path before triggering the maven build, it will be nice to have the `/tmp/src/` configurable to allow builds using the image to set them via env variable. 

e.g. SRC_DIR=${SRC_DIR:-'/tmp/src'}

CC: @cescoffier

**Comment by cescoffier** [comment]
It has been fixed.
