### ISSUE TITLE
Add xargs to build images

### ISSUE THREAD

**Issue by Sopka** [quarkusio/quarkus-images#274]
The gradle wrapper script forces you to have xargs installed. 

See [Gradle Issue 19682](https://github.com/gradle/gradle/issues/19682)

In my case I cannot use the quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 to build a gradle project.

Including the findutils package would solve the issue...

```
.installer("microdnf")
                .user("root")
                .install("tar", "gzip", "gcc", "glibc-devel", "zlib-devel", "shadow-utils", "unzip", "gcc-c++", "findutils")
```

**Comment by cescoffier** [comment]
Thanks! Can you open a PR?

**Comment by cescoffier** [comment]
I'm actually wondering the image you are using. Builder images should not include Gradle. Only the s2i does.

**Comment by Sopka** [comment]
Pull request added: https://github.com/quarkusio/quarkus-images/pull/275

I do not need gradle in the builder image. The Java project's GIT repository includes the gradle wrapper script that downloads a fixed version of gradle during the build. See https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by ThoSap** [comment]
I always added the `findutils` package to my custom `Dockerfile.multistage-native` Dockerfile so Gradle works.
This is a welcome change, as I no longer need to do that, thanks!
```Dockerfile
RUN microdnf install -y --setopt=install_weak_deps=0 findutils \
 && microdnf clean all -y \
 && [ ! -d /var/cache/yum ] || rm -rf /var/cache/yum
```

**Comment by cescoffier** [comment]
Fixed.
