### ISSUE TITLE
Minimal S2I build that support binary deployments

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus-images#29]
I've talked to some customer using Quarkus on OpenShift and a common pattern is to have a build infrastructure outside or inside OpenShift where artifacts like JARs and native are built outside in a separate flow from S2I. That could be to for example build the native using a local container or building it in Jenkins or Tekton. Having a S2I binary based on the UBI 7 or UBI 8 would make it much easier to deploy Quarkus native application to OpenShift

The user flow for a local build would then look something like this:
1. The user builds the native locally
```sh
./mvnw package -Pnative -Dnative-image.docker-build=true
```
2. The user creates a build config and uploads the binary
```sh
oc new-build <S2I-container-image> --name=<app-name> --binary
oc start-build <app-name> --from-file target/*-runner
```
3. When the build finishes the result is a minimal image based on UBI with the application running and the user can create an application with the following command

```sh
oc new-app <app-name>
```

The drawback is that for the S2I to be minimal it should only support binary deployment. E.g. you cannot point it to a source directly so it needs to produce an error message if someone tries to use it with source builds.

**Comment by cescoffier** [comment]
For the record, @tqvarnst started working on something: https://github.com/tqvarnst/quarkus-binary-s2i
