### ISSUE TITLE
Wrong link under quarkus-images/modules/quarkus-native-s2i-scripts/README.md

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus-images#37]
## Issue

There is still a badly displayed link (see screenshot) which is wrong when you click on it as Quarkus web site replies with 404

![Screenshot 2019-09-09 12 11 36](https://user-images.githubusercontent.com/463790/64522801-2459cd00-d2fb-11e9-9bad-81cde0ab0095.png)

**Comment by cescoffier** [comment]
oh, that's just because I can't write a markdown link....
