### ISSUE TITLE
The native image binary should retain its original name

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus-images#58]
We should investigate if the following [line](https://github.com/quarkusio/quarkus-images/blob/master/modules/quarkus-native-binary-s2i-scripts/s2i/assemble#L18) actually needs to rename the native image binary, or its a matter of convenience.

On the quarkus tooling side, it does seem a little bit awkward and we were wondering if we could change that.

**Comment by Ladicek** [comment]
From the dicsussion in https://github.com/quarkusio/quarkus/pull/7749, I thought it's a rename, but it looks like it's a copy? (I wonder why not a symlink...) If it's a copy, then the `quarkus-container-image-s2i` extension could just ignore it and invoke the original binary?

Ah, probably not, there's the `chmod +x` part to it...

**Comment by cescoffier** [comment]
It copies the artifacts to the working directory. An alternative would be a symbolic link, a move would also be possible.

So, what's the real need?  Having the original name? Not moving it to this `QUARKUS_HOME? 

And yes @Ladicek seems like there is too much `chmod +x` :-)

**Comment by Ladicek** [comment]
I think we should retain the original name.

(I didn't notice it copies from `/tmp/src` to `/home/quarkus`. That makes sense, though it should probably be either a move or a symlink.)

**Comment by Karm** [comment]
Closing as Out of Date as I couldn't find any contemporary followup. Reopen, if it is still disturbing your force these days.
