### ISSUE TITLE
s2i native image builder doesn't respect multi-module project

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-images#60]
The `assemble` script in the `quarkus-native-s2i-scripts` builder image always assumes that an artifact is in the `target` directory of a maven build. 

```bash
# lines 34 - 37
BUILD_DIR=target
mvn package -Pnative -e -B \
    -DskipTests -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true \
    -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true

# line 41
cp -v ${BUILD_DIR}/*-runner ${QUARKUS_HOME}/application
```

Using environment variables a user can tell maven to only build a sub-module, and in that case the built artifact won't be in `target`. Instead it'll be in `<sub_module_path>/target`.

See an ongoing discussion in https://github.com/kenfinnigan/kraken-demo/pull/2 around this issue.

**Comment by andreabattaglia** [comment]
Having the same issue with my multi-module project.
To compile in jvm mode I'd use the following script

```
oc new-build registry.access.redhat.com/ubi8/openjdk-11~https://github.com/qiot-project/qiot-datahub-collector.git \
  --context-dir=. --name=gas-collector-service  --build-env='ARTIFACT_DIR=qiot-datahub-collector-gas/target' \
  --build-env='MAVEN_ARGS= -pl qiot-datahub-collector-gas -am'
```
And the build-env ARTIFACT_DIR makes it possible to look for the binary into the specified directory.

Using the native image...

```
oc new-build quay.io/quarkus/ubi-quarkus-native-s2i:20.3.1-java11~https://github.com/qiot-project/qiot-datahub-collector.git \
--context-dir=.  --name=gas-collector-service --build-env='BUILD_DIR=qiot-datahub-collector-gas/target' \
--build-env='MAVEN_ARGS=install -pl qiot-datahub-collector-gas -am'
```

**ARTIFACT_DIR** or **BUILD_DIR** build-envs are ignored and I get the following error from the OCP build task:

```
+ cp -v 'target/*-runner' /home/quarkus/application
cp: cannot stat 'target/*-runner': No such file or directory
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
```
