### ISSUE TITLE
error while loading shared libraries: libstdc++.so.6

### ISSUE THREAD

**Issue by dicastro** [quarkusio/quarkus-images#61]
I've got the this error when running the container with the image `cescoffier/native-base:latest`:

`./application: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`

Is it because there is missing some library in the image? Could it be solved by compiling the image to avoid the use of libstdc++.so.6?

I've compiled the application with the command in the documentation:

`mvn package -Pnative -Dquarkus.native.container-runtime=docker`

And I've built the application from within a docker container with this image `quay.io/quarkus/centos-quarkus-maven:19.3.1-java8`. I've tried also with the version 20.0.0 with the same results.

However, if I run it using `registry.access.redhat.com/ubi8/ubi-minimal` image, it works.

**Comment by muratkarakas** [comment]
Hi,
I have  the same issue. With simple rest api dependecies it works but after adding  quarkus-smallrye-opentracing got the same error.

**Comment by dicastro** [comment]
That's true, the first time I tried to build a native image was with a simple rest api. After that I added more dependencies and functionality, and the native build started to fail.

I don't know which dependency is causing the issue. I thought that if I use only the quarkus dependencies, native build will work always.

This is my current list of dependencies:

`
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-jsonb</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-orm</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-scheduler</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-rest-client</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-cache</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-vertx</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-qute</artifactId>
</dependency>
`

**Comment by cescoffier** [comment]
The distroless base does not include `libstdc++.so.6`, we would need build a new base that includes it.

**Comment by dicastro** [comment]
And would it be possible to add it?

**Comment by cescoffier** [comment]
Yes, just need to be added in https://github.com/quarkusio/quarkus-images/blob/master/distroless/packages.bzl.

**Comment by kronostools** [comment]
After all this time I've come back to the subject. Which version of bazel should be used to build the image?

With version 3.3.1 the image compilation does not work for me. I've go this error:

`packages.bzl:3:1: file '@distroless//package_manager:package_manager.bzl' does not contain symbol 'dpkg_src'`

**Comment by cescoffier** [comment]
I'm using the same version.
However, I may have used a different (older) version when I did this work.

Le ven. 10 juil. 2020 à 08:17, kronostools <notifications@github.com> a
écrit :

**Comment by serrodcal** [comment]
I tried to solve this error in a [fork of the quarkus-images repo](https://github.com/serrodcal/quarkus-images), but unfortunately I got another error I don't know how to solve:

```
ERROR: Failed to load Starlark extension '@io_bazel_rules_go_name_hack//:def.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @io_bazel_rules_go_name_hack
This could either mean you have to add the '@io_bazel_rules_go_name_hack' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
``` 

All the changes I did are in this [commit](https://github.com/serrodcal/quarkus-images/commit/3f897ae20f9f5e2a565b210130ff7c6f56a1fffb), just in case someone know how to solve it...

> After all this time I've come back to the subject. Which version of bazel should be used to build the image?
> 
> With version 3.3.1 the image compilation does not work for me. I've go this error:
> 
> `packages.bzl:3:1: file '@distroless//package_manager:package_manager.bzl' does not contain symbol 'dpkg_src'`

**Comment by xtaixe** [comment]
Hi, FYI I tried to build a distroless image using bazel and the Google repo some time ago and I gave up... it seems some of the things in their repo around the package manager are internal and there's some cyclic dependency, so you need to prebuild the package_manager with `bazel build //package_manager:dpkg_parser.par` (or something like that and use --cpu=darwin if on Mac I think, I don't remember exactly) but even after figuring out and doing that I kept getting errors or couldn't get it working... Also, from what I could find, the "official" replacements (https://github.com/bazelbuild/rules_docker, https://github.com/bazelbuild/rules_pkg/tree/master/deb_packages) don't provide the same functionality or at least I couldn't figure out how to get them working to extract and build with the proper libraries (disclaimer: my knowledge of bazel and around those low level libs is zero though...).

Another option I tried was https://github.com/philipz/quarkus-minimal (which is mentioned in https://github.com/quarkusio/quarkus-quickstarts/pull/157) and I could build the image but we use a bunch of extensions (dynamodb, postgres, s3, sqs...) and I kept getting network errors/issues at runtime, so I guess not all required libraries were listed and copied...

I don't know when or if I'll have more time to try other things, but I wonder if https://github.com/oracle/graal/issues/2589 will help or we will still be missing libs or other stuff in our case... 

Another approach is described in https://jamesward.com/2020/05/07/graalvm-native-image-tips-tricks/ but is a bit more involved, so I guess it would be good to figure out first if the new GraalVM flag from the issue above is enough...

My 2 cents.

**Comment by kronostools** [comment]
Hi again,

I've managed to build a distroless image. Instead of using the distroless image of quarkus (https://github.com/quarkusio/quarkus-images/tree/master/distroless) I've used the distroless image of google (https://github.com/GoogleContainerTools/distroless)

To build the image I've used Ubuntu 16.04.4 under the WLS of windows. In Ubuntu, I've installed bazel (3.2.0, required by the google distroless).

**(After cloning the google distroless repo I had to change the line endings of all sh scripts to use the linux ones. I have not checked if it is an issue with my git config or if the files have been commited wrongly)**

It is required to build the `package_manager` before building the image:

```
bazel-3.2.0 build --host_force_python=PY2 //package_manager:dpkg_parser.par
```

(It is forced to use Python 2, because it is the default version already installed in ubuntu 16.04)

Once the `package_manager` has been built, the `cc` image can be built:

```
bazel-3.2.0 build --host_force_python=PY2 //cc:cc_debian10
```

(there are two versions of this image that can be built `debian10` and `debian9`)

Once the `cc` image is built, it can be loaded in docker local registry:

```
bazel-3.2.0 run --host_force_python=PY2 //cc:cc_debian10
```

An image `bazel/cc:cc_debian10` (21.3 MB) is loaded and ready to use with docker.

```
# Example Dockerfile
FROM bazel/cc:cc_debian10
COPY target/*-runner /application

EXPOSE 8080

CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.profile=pro"]
```

**I had to add an extra dependency to de cc image: `DISTRO_PACKAGES[distro_suffix]["zlib1g"],` to start the quarkus application** (the `libstdc++6` dependency, that originated this issue, is already present in the `cc` image)

**Comment by maxday** [comment]
Hi ! I have managed to build a distroless image : https://github.com/quarkusio/quarkus/issues/8974
@cescoffier

**Comment by cescoffier** [comment]
closing as it's now merged.
