### ISSUE TITLE
1.3.1-Final quarkus projects are not working anymore with the latest release of centos-quarkus-maven

### ISSUE THREAD

**Issue by sunix** [quarkusio/quarkus-images#63]
I have been trying to build https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started
- which has just been updated to 1.3.1-Final
- with  [quay.io/quarkus/centos-quarkus-maven:20.0.0-java8](https://quay.io/repository/quarkus/centos-quarkus-maven)

Before the version update, the maven build was working fine
Now it is failing:
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.097 s
[INFO] Finished at: 2020-04-06T09:33:54Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.1.Final:dev (default-cli) on project getting-started: Detected Maven Version (3.6.1)  is not supported, it must be in [3.6.2,). -> [Help 1]
[ERROR]
```

Looks like the version 1.3.1-Final is requiring maven 3.6.2.

**Comment by cescoffier** [comment]
Wondering why it's not fixed with https://github.com/quarkusio/quarkus-images/pull/54.

**Comment by cescoffier** [comment]
@sunix can you check when you pull the image? 

```
❯ docker run -it quay.io/quarkus/centos-quarkus-maven:20.0.0-java8 bash
[quarkus@74e873d3166e project]$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /opt/graalvm/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.19.76-linuxkit", arch: "amd64", family: "unix"
```

**Comment by sunix** [comment]
@cescoffier strange, I am checking with @svor as he reported that problem https://github.com/eclipse/che-devfile-registry/pull/220#pullrequestreview-388089776
Will keep you updated.

**Comment by svor** [comment]
just checked it again and can confirm that it works nice

**Comment by cescoffier** [comment]
Thanks for the feedback!
