### ISSUE TITLE
library initialization failed - unable to get max # of allocated fds

### ISSUE THREAD

**Issue by andreabattaglia** [quarkusio/quarkus-images#71]
Hello everybody,

more than an issue, this is a support request, cause I'm not sure whether I'm missing anything in the container image creation.

In order to build the container image for aarch64, I've created the following environment:

- Host:
OS: Fedora 32 amd64
hypervisor: QEMU/KVM
- Guest:
CPU: aarch64/Cortex-A53 - 4 core assigned
RAM: 8Gb
OS: Fedora 32 Minimal aarch64 
The remaining meaningful information from the docker logs (please find the full log attached)

2020-05-03 03:36:10,353 cekit        DEBUG    {'Platform': {'Name': 'Docker Engine - Community'}, 'Components': [{'Name': 'Engine', 'Version': '19.03.3', 'Details': {'ApiVersion': '1.40', 'Arch': 'arm64', 'BuildTime': '2019-10-08T01:00:39.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'a872fc2', 'GoVersion': 'go1.12.10', 'KernelVersion': '5.6.7-300.fc32.aarch64', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.2.13', 'Details': {'GitCommit': '7ad184331fa3e55e52b890ea95e65ba581ae3429'}}, {'Name': 'runc', 'Version': '1.0.0-rc10', 'Details': {'GitCommit': 'dc9208a3303feef5b3839f4323d9beb36df0a9dd'}}, {'Name': 'docker-init', 'Version': '0.18.0', 'Details': {'GitCommit': 'fec3683'}}], 'Version': '19.03.3', 'ApiVersion': '1.40', 'MinAPIVersion': '1.12', 'GitCommit': 'a872fc2', 'GoVersion': 'go1.12.10', 'Os': 'linux', 'Arch': 'arm64', 'KernelVersion': '5.6.7-300.fc32.aarch64', 'BuildTime': '2019-10-08T01:00:39.000000000+00:00'}

The following changes have been applied to the Guest OS:

`sudo sysctl -w fs.file-max=500000`

The following changes have been applied to the quarkus-maven scripts and templates:

- build-tooling-images.sh
Just building version 20.0.0-java11
added the line `pip install -r requirements.txt`

- requirements.txt
new file to make virtualenv load the dependencies `docker` and `docker-squash`

- modules/graalvm/20.0.0-java11/module.yaml
replaced `amd64` with `aarch64`
replaced md5 value to reflect the proper md5sum of the graalvm compressed archive for aarch64

- modules/common-packages/module.yaml
Added `libstdc++-static` to the list of the dependencies to be installed (honestly, just a tentative workaround)

The build process exits with an error when trying to installing the native image
`/opt/graalvm/bin/gu --auto-yes install native-image` 
Error message: ibrary initialization failed - unable to get max # of allocated fds

I have the feeling the error is related to the permissions assigned to the user running the gu command inside the container, but tbh I'm not into those details yet and I'm keen to learn.

Any help will be much appreciated

[output.log](https://github.com/quarkusio/quarkus-images/files/4569955/output.log)

**Comment by cescoffier** [comment]
I don't have any experience with aarch64, @dmlloyd By any chance, do you know if it's supported? It seems that `gu` cannot be run.

**Comment by dmlloyd** [comment]
It ran without any problem on my physical aarch64 system.  I think you are correct that it must be some sort of permissions issue.  The GraalVM error gives no hints unfortunately; it simply seems to kill the process with SIGABRT (i.e. using the `abort()` syscall) without printing the errno message.

**Comment by andreabattaglia** [comment]
Guys,
Thanks for replying so quickly.
A couple of additional questions:
Any idea who I could reach out to to get specific support on this? 
@dmlloyd any chance you could share the outcome of the successful execution of the build on aarch64?

**Comment by dmlloyd** [comment]
I haven't tried to build a container image; I only ran the `gu` command.  I'm not a Docker expert unfortunately.

**Comment by Karm** [comment]
Hello, we have a new suite of both arm64 and amd64 Linux containers for Mandrel:

```
quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
quay.io/quarkus/ubi-quarkus-mandrel-builder-image:21.3-java17
```

I tested both amd64 (Xeons, Skylake and Ivy Bridge EP) and aarch64 (Ampere Altra) variants on CentOS 8 Stream. 

Closing this issue as Out of Date.
