### ISSUE TITLE
Possibility to run unit tests when building native application?

### ISSUE THREAD

**Issue by josequaresma** [quarkusio/quarkus-images#8]
Hi,

Would it make sense to be able to run the unit tests when packaging the application in native mode? I can see that we are [skipping the tests](https://github.com/quarkusio/quarkus-images/blob/4c497867232554008519c559bb57001d66e9dd81/centos-quarkus-native-s2i/s2i/assemble#L11), but I think it could be useful to be able to run them? Maybe we could use an Environment variable?

**Comment by Karm** [comment]
I'd close this as Out of Date, although it seems to still be the case today for s2i:

https://github.com/quarkusio/quarkus-images/blob/main/quarkus-native-s2i/src/main/resources/scripts/assemble#L40

@josequaresma If this is something disturbing your workflow these days, reopen please.
