### ISSUE TITLE
centos-quarkus-maven still referenced (deprecated?)

### ISSUE THREAD

**Issue by jmtd** [quarkusio/quarkus-images#81]
The image centos-quarkus-maven is still listed in the README file (and there are a few other references in the repo to it)

I think (since #22) you no longer base on centos, and [the quay.io pages](https://quay.io/repository/quarkus/centos-quarkus-maven?tag=latest&tab=tags) suggest it has not been updated (due to the number of security issues) despite the "last modifed" of 5 days ago (at the time of writing)

**Comment by cescoffier** [comment]
We still produce the centos-quarkus-maven image (aka the tooling image). 
The descriptor is the following: https://github.com/quarkusio/quarkus-images/blob/master/quarkus-tooling.yaml

It uses centos:7 which, unfortunately, has some security issues. I've tried to switch to centos:8 without success.

**Comment by maxandersen** [comment]
fixed already.
