### ISSUE TITLE
s2i builder should use commonly used paths

### ISSUE THREAD

**Issue by quintesse** [quarkusio/quarkus-images#85]
Most official S2I builder images created by RH put the S2I scripts in `/usr/libexec/s2i` while the Quarkus S2I builders use a different path `/usr/local/s2i`.

This is indeed supported by S2I but it seems that some tools (in my case http://quay.io/openshift-pipeline/s2i which is an image that  runs `s2i`) just assume the paths are always the same and have them hard-coded. This might also be because inspecting the builder image for the label that defines the correct path is sometimes hard.

Now of course those tools should be fixed, but at the same time I think the Quarkus S2I builder images should not deviate from the commonly used values without good reason.

**Comment by maxandersen** [comment]
@cescoffier any comments on this ?

**Comment by quintesse** [comment]
He's on PTO :-)

**Comment by quintesse** [comment]
Btw, to reproduce one has to use the `--as-dockerfile` option, just running `s2i build` works fine. But when asking S2I to generate a Dockerfile it generates it with default paths. Not sure if that should be considered a problem with S2I or not.

**Comment by cescoffier** [comment]
Ok, let's change the location

**Comment by cescoffier** [comment]
Note: the openshift documentation and resources are using both locations:

* https://www.openshift.com/blog/create-s2i-builder-image
* https://github.com/openshift/source-to-image/blob/aca6e1b30336192ce99b409caf82c85cad84eeef/Dockerfile

**Comment by quintesse** [comment]
> Note: the openshift documentation and resources are using both locations:

Yeah, it's definitely supported to have different paths. Not sure if practise just isn't following theory or if tools like the one I mentioned are just broken.
