### ISSUE TITLE
Default US-ASCII encoding in images too limiting

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus-images#86]
It would appear to be `ANSI_X3.4-1968` or `US-ASCII` which is causing issues when native images produced in the image are used with other character encoding.

UTF8 is a much better default and resolves the issue. See https://github.com/quarkusio/quarkus/issues/11222 for more info.

**Comment by galderz** [comment]
Btw, this affects all images, no matter whether GraalVM or Mandrel.

**Comment by galderz** [comment]
Please assign issue to me.

**Comment by rsvoboda** [comment]
Fix for this issue needs to be backported to product image.
@karm fyi, see also quarkusio/quarkus#11222
