### ISSUE TITLE
Create major.minor (e.g. 20.1-java11) floating tag in quay for mandrel images

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus-images#91]
As discussed in https://github.com/graalvm/mandrel/issues/95 we would like to have "floating" tags for mandrel images.

The floating tags would be based on the `major.minor` part of the tag and point to the latest `major.minor.micro.patch.Final` tag, i.e., `20.1-java11` would point to `20.1.0.1.Final-java11` today and later to `20.1.0.2.Final` when released.

Ideally this process should be automated in https://github.com/quarkusio/quarkus-images/blob/master/.github/build-mandrel-images.sh but I see the following issue.
When a new image is created and pushed on quay it is not made public until someone does this manually. 
If we are to automate the update of the floating tags how would that work? 
We would essentially have the floating tag (which should be public) point to a private tag and thus break builds until the new tag becomes public.

\cc @galderz @cescoffier

**Comment by cescoffier** [comment]
yes, unfortunately right now we don't have such a support tin the bash script.

**Comment by zakkak** [comment]
> Only for new images, not new versions / tags.

OK, then that would work just fine. I'll prepare a PR :)
